spring.application.name=cache_redis
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.redis.time-to-live=10m

## DATABASE
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClasseName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

## CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2

## FORMAT SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

